# Generated by Django 4.1.7 on 2023-11-14 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('ADM_SITE', 'Administrador do site'), ('PROFESSOR', 'Professor'), ('ALUNOS', 'Aluno')], max_length=30)),
                ('grupo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_grupo', to='auth.group')),
            ],
        ),
    ]
