# Generated by Django 4.1.7 on 2023-12-16 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('celular', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=300, null=True)),
                ('ativo', models.CharField(choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=1)),
                ('sexo', models.CharField(blank=True, choices=[('F', 'Feminino'), ('M', 'Masculino'), ('N', 'Não informado')], max_length=1, null=True)),
                ('nascimento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlunoPacote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_contratacao', models.DateField()),
                ('data_validade', models.DateField()),
                ('ativo', models.CharField(choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=1)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.aluno')),
            ],
            options={
                'verbose_name_plural': 'Aluno - Pacote',
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativa', models.CharField(choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='aula_atualizado_por', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='aula_criado_por', to=settings.AUTH_USER_MODEL)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='aula_professor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiaReservado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Dias de reserva especiais',
            },
        ),
        migrations.CreateModel(
            name='Pacote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qtd_aulas_semana', models.IntegerField()),
                ('qtd_participantes', models.IntegerField()),
                ('ativo', models.CharField(choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TipoGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('ADM_SITE', 'Administração do site'), ('PROFESSOR', 'Professor'), ('ATENDIMENTO', 'Atendimento'), ('ALUNOS', 'Aluno')], max_length=30)),
                ('grupo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_grupo', to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
                ('data_horario_ini', models.DateTimeField(blank=True, null=True)),
                ('data_horario_fim', models.DateTimeField(blank=True, null=True)),
                ('dia_inteiro', models.CharField(choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=1)),
                ('ativo', models.CharField(choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=1)),
                ('cancelado_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelamento', models.TextField(blank=True, null=True)),
                ('aula_unica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.aula')),
                ('cancelado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('especial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.diareservado')),
            ],
        ),
        migrations.CreateModel(
            name='Recorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(blank=True, null=True)),
                ('horario_ini', models.CharField(max_length=5)),
                ('horario_fim', models.CharField(max_length=5)),
                ('dia_inteiro', models.CharField(choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=1)),
                ('ativo', models.CharField(choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=1)),
                ('aula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.aula')),
            ],
            options={
                'verbose_name_plural': 'Recorrencia de aulas',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(blank=True, max_length=11)),
                ('celular', models.CharField(blank=True, max_length=30)),
                ('foto_perfil', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AulaParticipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conferido', models.CharField(choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=1)),
                ('conferido_em', models.DateTimeField(blank=True, null=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.aula')),
                ('conferido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='aulaaluno_conferido_por', to=settings.AUTH_USER_MODEL)),
                ('contratante', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='aula_contratante', to='backend.aluno')),
                ('pacote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.pacote')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='aula_participante', to='backend.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='AlunoPacoteHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('desativado_em', models.DateField(blank=True, null=True)),
                ('data_contratacao', models.DateField()),
                ('data_validade', models.DateField()),
                ('aluno_pacote', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.alunopacote')),
                ('desativado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Aluno - Pacote | Histórico',
            },
        ),
        migrations.AddField(
            model_name='alunopacote',
            name='pacote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.pacote'),
        ),
        migrations.AlterUniqueTogether(
            name='alunopacote',
            unique_together={('aluno', 'pacote')},
        ),
    ]
