# Generated by Django 4.1.7 on 2023-12-13 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('celular', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=300, null=True)),
                ('ativo', models.CharField(choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=1)),
                ('sexo', models.CharField(blank=True, choices=[('F', 'Feminino'), ('M', 'Masculino'), ('N', 'Não informado')], max_length=1, null=True)),
                ('nascimento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pacote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qtd_aulas_semana', models.IntegerField()),
                ('qtd_participantes', models.IntegerField()),
                ('ativo', models.CharField(choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=1)),
                ('tipo', models.CharField(choices=[('AVULSO', 'Avulso'), ('NORMAL', 'Normal')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TipoGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('ADM_SITE', 'Administração do site'), ('PROFESSOR', 'Professor'), ('ATENDIMENTO', 'Atendimento'), ('ALUNOS', 'Aluno')], max_length=30)),
                ('grupo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_grupo', to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(blank=True, max_length=11)),
                ('celular', models.CharField(blank=True, max_length=30)),
                ('foto_perfil', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('N', 'Não informado')], max_length=1)),
                ('nascimento', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlunoPacote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.CharField(choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('desativado_em', models.DateField(blank=True, null=True)),
                ('data_contratacao', models.DateField()),
                ('data_validade', models.DateField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.aluno')),
                ('desativado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('pacote', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.pacote')),
            ],
            options={
                'verbose_name_plural': 'Aluno - Pacote',
            },
        ),
    ]
