# Generated by Django 4.1.7 on 2023-12-13 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativa', models.CharField(choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='aula_atualizado_por', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='aula_criado_por', to=settings.AUTH_USER_MODEL)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='aula_professor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiaReservado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Dias de reserva especiais',
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.aluno'),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
                ('data_horario_ini', models.DateTimeField(blank=True, null=True)),
                ('data_horario_fim', models.DateTimeField(blank=True, null=True)),
                ('dia_semana', models.IntegerField(blank=True, null=True)),
                ('dia_inteiro', models.CharField(choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=1)),
                ('ativo', models.CharField(choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=1)),
                ('cancelado_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelamento', models.TextField(blank=True, null=True)),
                ('aula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.aula')),
                ('cancelado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('especial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.diareservado')),
            ],
        ),
        migrations.CreateModel(
            name='AulaParticipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conferido', models.CharField(choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=1)),
                ('conferido_em', models.DateTimeField(blank=True, null=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.aula')),
                ('conferido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='aulaaluno_conferido_por', to=settings.AUTH_USER_MODEL)),
                ('contratante', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='aula_contratante', to='backend.aluno')),
                ('pacote', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.pacote')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='aula_participante', to='backend.aluno')),
            ],
        ),
    ]
