# Generated by Django 4.1.7 on 2023-12-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_aula_ativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorrencia',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
