# Generated by Django 4.1.7 on 2023-12-04 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0002_alunopacote_desativado_em_alunopacote_desativado_por'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alunopacote',
            options={'verbose_name_plural': 'Aluno - Pacote'},
        ),
        migrations.AlterField(
            model_name='alunopacote',
            name='desativado_em',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alunopacote',
            name='desativado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
