# Generated by Django 4.1.7 on 2023-12-13 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_aula_diareservado_aluno_responsavel_reserva_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='responsavel',
        ),
    ]
