# Generated by Django 4.1.7 on 2023-11-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_tipogrupo_tipo_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='celular',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='perfil',
            name='foto_perfil',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
