# Generated by Django 4.1.7 on 2023-12-25 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_recorrencia_criado_em'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='aula_unica',
            new_name='aula',
        ),
    ]
