# Generated by Django 4.1.7 on 2023-12-14 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0003_remove_aluno_responsavel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacote',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='nascimento',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='sexo',
        ),
        migrations.AlterField(
            model_name='aulaparticipante',
            name='pacote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.pacote'),
        ),
        migrations.AlterUniqueTogether(
            name='alunopacote',
            unique_together={('aluno', 'pacote')},
        ),
        migrations.CreateModel(
            name='AlunoPacoteHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('desativado_em', models.DateField(blank=True, null=True)),
                ('data_contratacao', models.DateField()),
                ('data_validade', models.DateField()),
                ('aluno_pacote', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.alunopacote')),
                ('desativado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Aluno - Pacote | Histórico',
            },
        ),
        migrations.RemoveField(
            model_name='alunopacote',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='alunopacote',
            name='desativado_em',
        ),
        migrations.RemoveField(
            model_name='alunopacote',
            name='desativado_por',
        ),
    ]
