# Generated by Django 4.1.7 on 2023-12-06 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0003_alter_alunopacote_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='agenda',
            name='backend_agenda_aula_ou_especial',
        ),
        migrations.AddField(
            model_name='agenda',
            name='ativo',
            field=models.CharField(choices=[('S', 'SIM'), ('N', 'NÃO')], default='S', max_length=1),
        ),
        migrations.AddField(
            model_name='agenda',
            name='cancelado_em',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='agenda',
            name='cancelado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agenda',
            name='motivo_cancelamento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='agenda',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('aula__isnull', True), ('reserva_especial__isnull', False)), models.Q(('ativo', 'S'), ('aula__isnull', False), ('reserva_especial__isnull', True)), _connector='OR'), name='backend_agenda_aula_ou_especial'),
        ),
    ]
