# Generated by Django 4.1.7 on 2023-12-06 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0005_alter_agenda_aula_alter_agenda_cancelado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='cancelado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='aula_cancelado_por', to=settings.AUTH_USER_MODEL),
        ),
    ]
