# Generated by Django 4.1.7 on 2023-12-07 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0006_alter_aula_cancelado_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='cancelado_em',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='cancelado_por',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='motivo_cancelamento',
        ),
        migrations.AlterField(
            model_name='aulaaluno',
            name='conferido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aulaaluno',
            name='conferido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='aulaaluno_conferido_por', to=settings.AUTH_USER_MODEL),
        ),
    ]
