# Generated by Django 4.1.7 on 2023-12-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_remove_aula_cancelado_em_remove_aula_cancelado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='celular',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='email',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
